project:
  type: website
  render: 
    - "*.qmd"
    - "!_template.qmd"
    - "!README.md"

website:
  title: ""
  bread-crumbs: false
  twitter-card: true
  open-graph: true
  # back-to-top-navigation: true

  navbar:
    logo: assets/images/logo.png
    logo-alt: "Cyber2A"
    logo-href: https://cyber2a.github.io
    tools:
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
    left:
      - href: index.qmd
        text: Home
      - text: People
        menu:
          - text: "Core Project Team"
            href: people/core-project-team.qmd
          - text: "Project Collaborators"
            href: people/project-collaborators.qmd
          - text: "Advisory Board"
            href: people/advisory-board.qmd
      - text: "News"
        href: news/index.qmd
      - text: Webinars
        href: webinars/index.qmd
#        menu: 
#          - text: "Upcoming Webinars"
#            href: webinars/upcoming-webinars.qmd
#          - text: "Past Webinars"
#            href: webinars/past-webinars.qmd
      - text: "Workshop"
        href: workshop/index.qmd
#      - text: "Discussions"
#        href: discussions/index.qmd
      - text: "CFP2025"
        href: cfp2025.qmd
#      - text: "GeoAI Challenge"
#        menu:
#          - text: "Overview"
#            href: challenge/index.qmd
#          - text: "Dataset"
#            href: challenge/dataset.qmd
#          - text: "Participate"
#            href: challenge/participate.qmd
#          - text: "Resources"
#            href: challenge/resources.qmd
    
  sidebar:

    - title: "Workshop"
      collapse-level: 1
      style: "floating"
      background: light
      contents:
        - text: "Workshop Information"
          href: workshop/index.qmd
        - section: "Workshop Curriculum Preview"
          contents:
          - text: "<b>1. Introduction to AI and Arctic science</b>"
          - text: "---"
          - text: "\u2022 Breaking the ice with AI in Arctic Science"
            href: workshop/preview/breaking-the-ice-with-ai-in-arctic-science.qmd
          - text: "\u2022 AI for everyone: an introductory overview"
            href: workshop/preview/ai-for-everyone.qmd
          - text: "\u2022 Guest lecture (Anna)"
            href: workshop/preview/guest-lecture-anna.qmd
          - text: "\u2022 The Fun and frontiers of AI: innovation, imagination, interaction"
            href: workshop/preview/the-fun-and-frontiers-of-ai.qmd

          - text: "<b>2. Data management and preparation for AI</b>"
          - text: "---"
          - text: "\u2022 AI-ready data in Arctic research: principles and practices"
            href: workshop/preview/ai-ready-data-in-arctic-research.qmd
          - text: "\u2022 Guest lecture: unveiling the ARTS dataset for a thawing frontier"
            href: workshop/preview/guest-lecture-yili-rts-introduction.qmd
          - text: "\u2022 Data annotation: the foundation of deep learning models"
            href: workshop/preview/data-annotation.qmd
          - text: "\u2022 Hands on lab: data annotation"
            href: workshop/preview/hands-on-lab-data-annotation.qmd

          - text: "<b>3. AI fundamentals and techniques</b>"
          - text: "---"
          - text: "\u2022 The building blocks of neural networks and deep learning"
            href: workshop/preview/the-building-blocks-of-nn-and-dl.qmd
          - text: "\u2022 Introduction to PyTorch: core functionalities and advantages"
            href: workshop/preview/intro-to-pytorch.qmd
          - text: "\u2022 Hands-on-lab: PyTorch"
            href: workshop/preview/hands-on-lab-pytorch.qmd
          - text: "\u2022 Exploring advanced neural networks: semantic segmentation"
            href: workshop/preview/exploring-advanced-neural-networks.qmd
          - text: "\u2022 Introduction to deep learning libraries for image analysis"
            href: workshop/preview/intro-to-dl-libraries-for-image-analysis.qmd
          - text: "\u2022 Hands-on-lab: MMSegmentation"
            href: workshop/preview/hands-on-lab-mmsegmentation.qmd


          - text: "<b>4. Advanced AI workflows and models</b>"
          - text: "---"
          - text: "\u2022 AI workflows and MLOps: from development to deployment"
            href: workshop/preview/ai-workflows-and-mlops.qmd
          - text: "\u2022 Hands-on-lab: AI workflows"
            href: workshop/preview/hands-on-lab-ai-workflows.qmd
          - text: "\u2022 Foundation models: the cornerstones of modern AI"
            href: workshop/preview/foundation-models.qmd
          - text: "\u2022 Hands-on-lab: foundation models"
            href: workshop/preview/hands-on-lab-foundation-models.qmd

          - text: "<b>5. Ethics and social implications of AI</b>"
          - text: "---"
          - text: "\u2022 AI ethics"
            href: workshop/preview/ai-ethics.qmd
          - text: "\u2022 Socially responsible AI"
            href: workshop/preview/socially-responsible-ai.qmd
          - text: "\u2022 Reproducibility"
            href: workshop/preview/reproducibility.qmd   

    - title: "GeoAI Challenge"
      collapse-level: 1
      style: "floating"
      background: light
      contents:
        - text: "Overview"
          href: challenge/index.qmd
        - text: "Dataset"
          href: challenge/dataset.qmd
        - text: "Participate"
          href: challenge/participate.qmd
        - text: "Resources"
          href: challenge/resources.qmd
     

  page-footer:
    background: dark
    left: |
      Copyright &copy; Cyber2A. All Rights Reserved. [View Stats](http://statcounter.com/p12923770/summary/?guest=1) <br>
      This website was created with 
      [![](/assets/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)

    center: 
      - icon: github
      - text: Report an issue
        href: https://github.com/cyber2a/cyber2a-community/issues/new
      
    right: 
      - text: "Contact Us:"
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
      - icon: envelope
        href: mailto:cyber2a@googlegroups.com

format:
  html:
    theme: cosmo
    toc: false
    link-external-newwindow: true
    grid:
      body-width: 950px
    title-block-banner: assets/images/texture-bw.png
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    include-after-body: 
      - file: _statcounter.html

execute: 
  freeze: auto



