---
title: "Cyber2A Workshop"
---

# AI Workflows and MLOps: From Development to Deployment
Ben Galewsky, Sr. Research Software Engineer National Center for Supercomputing Applications (NCSA) University of Illinois Urbana-Champaign


## Overview
Machine learning models have become a vital tool for most branches of science. The process and tools for training these models on the lab's desktop is often fragile, slow, and not reproducible. In this workshop, we will introduce the concept of MLOps, which is a set of practices that aims to streamline the process of developing, training, and deploying machine learning models. We will use the popular open source MLOps tool, MLflow, to demonstrate how to track experiments, package code, and deploy models. We will also introduce Garden, a tool that allows researchers to publish ML Models as citable objects.

## Outline
* Introduction to MLOps
* Introduction to MLflow
* Tracking experiments with MLflow
* Packaging code with MLflow
* Deploying models with MLflow
* Publishing models with Garden

## Reference
* [MLflow](https://mlflow.org/)
* [Garden](https://thegardens.ai/)
