---
title: "Cyber2A Workshop"
---

# Introduction to PyTorch: Core Functionalities and Advantages

## Goal
This session introduces PyTorch, one of the most popular deep learning frameworks, known for its flexibility and ease of use. Participants will gain hands-on experience with PyTorch's core functionalities and apply them to a sample dataset, setting the stage for a subsequent hands-on session. The goal is to arm participants with the essential knowledge and confidence required to begin utilizing PyTorch in their deep learning endeavors, ensuring they're well-prepared for practical application and further exploration. 

## Outline
* Introduction to PyTorch
* Understanding PyTorch’s core functionalities
* Working with data in PyTorch
* Building a simple neural network in PyTorch
* Training a model
* Evaluating a model
* Conclusion and preparing for hands-on session

## Reference
* [https://pytorch.org](https://pytorch.org)
* [https://pytorch.org/tutorials/](https://pytorch.org/tutorials/)

